#!/bin/bash
# filter_lncRNA_50pct_PC.sh
#
# Filters lncRNA_introns_final.bed to remove all entries for lncRNA genes
# where >=50% of the gene body overlaps a protein-coding gene body
# (strand-ignored: removes both sense and antisense overlaps).
#
# Prerequisites (already generated by filter_lncRNA_PC_overlap.sh):
#   - protein_coding_genes_v49_basic.bed must exist in ANNOT_DIR
#   - lncRNA_genes_v49.bed must exist in ANNOT_DIR
#
# Run from any directory; all outputs go to ANNOT_DIR.

set -euo pipefail

ANNOT_DIR="/scratch/alpine/wist9668/reference/annotation/lnc_RNA"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PC_BED="${ANNOT_DIR}/protein_coding_genes_v49_basic.bed"
LNCRNA_GENES_BED="${ANNOT_DIR}/lncRNA_genes_v49.bed"
INPUT_BED="${ANNOT_DIR}/lncRNA_introns_final.bed"

OVERLAP_LIST="${ANNOT_DIR}/lncRNA_genes_50pct_PC.txt"
OUTPUT_BED="${ANNOT_DIR}/lncRNA_introns_50pct_PC_filt.bed"

ml miniforge

# --- Step 1: Find lncRNA genes with >=50% overlap with a PC gene body ---
echo "[1/2] Finding lncRNA genes with >=50% overlap with PC gene bodies..."
conda run -n hap1 bedtools intersect \
  -a "${LNCRNA_GENES_BED}" \
  -b "${PC_BED}" \
  -u -f 0.5 \
  | cut -f4 | sort -u > "${OVERLAP_LIST}"
echo "  lncRNA genes excluded (>=50% PC overlap): $(wc -l < "${OVERLAP_LIST}")"

# --- Step 2: Filter lncRNA introns BED ---
echo "[2/2] Filtering lncRNA_introns_final.bed..."
conda run -n hap1 python3 "${SCRIPT_DIR}/filter_lncRNA_introns.py" \
  "${OVERLAP_LIST}" \
  "${INPUT_BED}" \
  "${OUTPUT_BED}"

echo ""
echo "Done. Output: ${OUTPUT_BED}"
echo "  Input entries:  $(wc -l < "${INPUT_BED}")"
echo "  Output entries: $(wc -l < "${OUTPUT_BED}")"
